PhronesisConsole.o: PhronesisConsole.cpp
phrUtils.o: phrUtils.cpp phrUtils.hpp phronesisAnalyzerClientApi.hpp \
 PhronesisConsole.hpp
pyPhronesismodule.o: pyPhronesismodule.cpp phronesisAnalyzerClientApi.hpp
