doc:
	cd ./analyzer/analyzerLib/;  doxygen doxygenAnalyzerLib.cfg; cd ../../;
	cd ./analyzer/analyzerDBAPI/; doxygen doxygenAnalyzerDBAPI.cfg; cd ../../;
	cd ./analyzer/analyzerCore/; doxygen doxygenAnalyzerCore.cfg; cd ../../;
	cd ./analyzer/analyzerAgent/; doxygen doxygenAnalyzerAgent.cfg; cd ../../;
